const escape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function waveformHtml(script: string, css: string, source: string, nonce: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${escape(source)}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${escape(css)}"></head><body>
  <header><div class="brand"><span class="mark">∿</span><div><h1 id="filename">Waveform</h1><div id="file-info" class="muted">Reading trace…</div></div></div><div class="header-actions"><button id="reload">Reload</button><button id="external">GTKWave ↗</button></div></header>
  <div id="trace-link" class="muted" role="status"></div>
  <div class="saved-views"><span id="view-context" class="muted"></span><label>View <select id="saved-view" aria-label="Saved waveform view"><option value="">Custom</option></select></label><button id="save-view">Save view…</button><button id="default-view">Use as default</button><button id="manage-view" aria-label="Manage saved view">⋯</button><span id="view-note" role="status" class="muted"></span></div>
  <div class="toolbar" role="toolbar" aria-label="Waveform controls"><button id="sidebar-toggle" title="Show or hide signal browser">Signals</button><span class="divider"></span><button id="fit" title="Fit entire trace (0)">Fit</button><button id="zoom-out" aria-label="Zoom out" title="Zoom out (-)">−</button><button id="zoom-in" aria-label="Zoom in" title="Zoom in (+)">+</button><button id="pan-left" aria-label="Pan left">←</button><button id="pan-right" aria-label="Pan right">→</button><span class="divider"></span><label class="radix-label">Drag <select id="gesture" aria-label="Pointer tool" title="Drag to place the cursor or zoom into a range. Esc cancels the drag."><option value="cursor">Cursor</option><option value="zoom">Zoom range</option></select></label><span class="cursor-time">Time <strong id="cursor-a">—</strong></span><button id="snap" title="Move the cursor to the nearest change of the selected signal">Snap cursor</button><button id="previous" title="Previous transition of focused signal">‹ Edge</button><button id="next" title="Next transition of focused signal">Edge ›</button><form id="time-form"><input id="go-time" aria-label="Go to time" placeholder="Go to time · 20 ns" autocomplete="off"><button type="submit" title="Move the cursor to the entered time">Go</button></form><label class="radix-label">Values <select id="radix" aria-label="Value format"><option value="auto">Auto (enum names)</option><option value="hex">Hex</option><option value="unsigned">Unsigned</option><option value="signed">Signed</option><option value="binary">Binary</option></select></label></div>
  <div class="workspace"><aside id="browser"><div class="section-head"><h2>Signals</h2><span id="signal-count" class="muted"></span></div><input id="search" type="search" aria-label="Search signals" placeholder="Search name or hierarchy…"><label class="scope-label">Hierarchy <select id="scope-filter" aria-label="Signal hierarchy"><option value="">All scopes</option></select></label><div id="catalogue"></div><div id="search-info" class="muted"></div></aside>
  <main><div class="signal-settings"><span id="focused-signal" title="Selected signal">Select a signal</span><label>Format <select id="signal-radix" aria-label="Selected signal format"><option value="default">Default</option><option value="auto">Auto (enum names)</option><option value="hex">Hex</option><option value="unsigned">Unsigned</option><option value="signed">Signed</option><option value="binary">Binary</option></select></label><label>Color <select id="signal-color" aria-label="Selected signal color"><option value="default">Default</option><option value="blue">Blue</option><option value="pink">Pink</option><option value="amber">Amber</option></select></label><button id="reset-signal">Reset signal style</button></div><div id="traces" tabindex="0" aria-label="Waveform traces"><div class="ruler-row"><div class="column-head">SIGNAL <span>VALUE</span></div><canvas id="ruler" aria-label="Time ruler"></canvas></div><div id="trace-rows"></div></div><div id="empty">Choose signals on the left to start exploring.</div></main></div>
  <footer><span id="status" role="status" aria-live="polite">Loading…</span><span id="range"></span></footer><script nonce="${nonce}" src="${escape(script)}"></script></body></html>`;
}
